version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: composepostgres
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "crypto_ticks"
    ports:
      - "5433:5432"
    restart: always
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8000:8080"
    environment:
      DATABASE_HOST: postgres
    links:
      - postgres
